import test from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import { applyHeaderToSource, renderHeader } from "../src/core/headers.js";
import { loadConfig } from "../src/core/config.js";
import { detectTestCommand, runDoc, runScan, runUpdate } from "../src/core/commands.js";
import { closeIndexDatabase, getArtifact, getRepoMeta, openIndexDatabase, upsertArtifact } from "../src/core/db.js";
import { validateRepo } from "../src/core/validate.js";

const execFileAsync = promisify(execFile);

async function initGitRepo(root) {
  await execFileAsync("git", ["init"], { cwd: root });
  await execFileAsync("git", ["config", "user.name", "Agentify Tests"], { cwd: root });
  await execFileAsync("git", ["config", "user.email", "agentify-tests@example.com"], { cwd: root });
  await execFileAsync("git", ["add", "."], { cwd: root });
  await execFileAsync("git", ["commit", "-m", "initial"], { cwd: root });
}

test("scan and doc generate required artifacts", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-update-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: true });
  await runScan(root, config);
  await runDoc(root, config);
  const result = await validateRepo(root, config);

  assert.equal(result.passed, true);
  assert.equal(await fs.stat(path.join(root, ".agents", "index.db")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, "docs", "modules", "auth.md")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, "AGENTIFY.md")).then(() => true), true);
  const summary = await fs.readFile(path.join(root, "AGENTIFY.md"), "utf8");
  assert.match(summary, /# AGENTIFY\.md/);
  assert.match(summary, /## Run Metrics/);
});

test("validateRepo allows tracked header-only code changes", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-validate-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  const filePath = path.join(root, "src", "auth", "index.ts");
  const source = "export const login = () => true;\n";
  await fs.writeFile(filePath, source);
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false });
  await runScan(root, config);
  await runDoc(root, config);

  const header = renderHeader({
    moduleName: "auth",
    summary: "Authentication entrypoints refreshed",
    relativePath: "src/auth/index.ts",
    stack: "ts"
  });
  const current = await fs.readFile(filePath, "utf8");
  await fs.writeFile(filePath, applyHeaderToSource(current, header), "utf8");

  const result = await validateRepo(root, config);

  assert.equal(result.passed, true);
});

test("validateRepo allows .agentify.yaml generated by init workflow", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-validate-config-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false });
  await runScan(root, config);
  await runDoc(root, config);
  await fs.writeFile(path.join(root, ".agentify.yaml"), "provider: local\n", "utf8");

  const result = await validateRepo(root, config);

  assert.equal(result.passed, true);
});

test("validateRepo allows project-scoped skill installations", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-validate-skills-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false });
  await runScan(root, config);
  await runDoc(root, config);
  await fs.mkdir(path.join(root, ".codex", "skills", "grill-me"), { recursive: true });
  await fs.writeFile(path.join(root, ".codex", "skills", "grill-me", "SKILL.md"), "# skill\n", "utf8");

  const result = await validateRepo(root, config);

  assert.equal(result.passed, true);
});

test("runUpdate emits percentage progress logs", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-progress-"));
  await fs.writeFile(path.join(root, "package.json"), JSON.stringify({
    scripts: {
      test: "node --test"
    }
  }, null, 2));
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.mkdir(path.join(root, "test"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await fs.writeFile(path.join(root, "test", "pass.test.js"), `import test from "node:test";
import assert from "node:assert/strict";

test("passes", () => {
  assert.equal(1, 1);
});
`);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false });
  const stderrChunks = [];
  const stdoutMessages = [];
  const originalWrite = process.stderr.write.bind(process.stderr);
  const originalLog = console.log;

  process.stderr.write = ((chunk, encoding, callback) => {
    stderrChunks.push(String(chunk));
    return originalWrite(chunk, encoding, callback);
  });
  console.log = (...args) => {
    stdoutMessages.push(args);
  };

  try {
    await runUpdate(root, config);
  } finally {
    process.stderr.write = originalWrite;
    console.log = originalLog;
  }

  const stderr = stderrChunks.join("");
  assert.match(stderr, /up: 0% starting/);
  assert.match(stderr, /up: 33% scan complete/);
  assert.match(stderr, /up: 67% doc complete/);
  assert.match(stderr, /up: 100% validation passed/);
  assert.match(stderr, /doc: 100% completed/);
  assert.ok(stdoutMessages.length > 0);
  assert.equal(await fs.stat(path.join(root, "output.txt")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, "agentify-report.html")).then(() => true), true);
  const output = await fs.readFile(path.join(root, "output.txt"), "utf8");
  const html = await fs.readFile(path.join(root, "agentify-report.html"), "utf8");
  assert.match(output, /\[agentify\] tests: passed/);
  assert.match(html, /All configured test cases passed\./);
  assert.match(html, /Copy rerun tests command/);
  assert.match(html, /Total tokens/);
});

test("runUpdate in ghost mode reuses a single artifact root", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-ghost-update-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, ghost: true });
  await runUpdate(root, config);

  const sessionRoot = path.join(root, ".current_session");
  const ghostRuns = (await fs.readdir(sessionRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory() && entry.name.startsWith("ghost_"))
    .map((entry) => entry.name);

  assert.equal(ghostRuns.length, 1);

  const artifactRoot = path.join(sessionRoot, ghostRuns[0]);
  assert.equal(await fs.stat(path.join(artifactRoot, ".agents", "index.db")).then(() => true), true);
  assert.equal(await fs.stat(path.join(artifactRoot, "AGENTIFY.md")).then(() => true), true);
  assert.equal(await fs.stat(path.join(artifactRoot, "ghost-report.json")).then(() => true), true);
  assert.equal(await fs.stat(path.join(artifactRoot, "output.txt")).then(() => true), true);
  assert.equal(await fs.stat(path.join(artifactRoot, "agentify-report.html")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, ".agents", "index.db")).then(() => true).catch(() => false), false);
  assert.equal(await fs.stat(path.join(root, "output.txt")).then(() => true).catch(() => false), false);
  assert.equal(await fs.stat(path.join(root, "agentify-report.html")).then(() => true).catch(() => false), false);
});

test("runUpdate with json emits only the final payload", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-update-json-"));
  await fs.writeFile(path.join(root, "package.json"), JSON.stringify({
    scripts: {
      test: "node --test"
    }
  }, null, 2));
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.mkdir(path.join(root, "test"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await fs.writeFile(path.join(root, "test", "pass.test.js"), `import test from "node:test";
import assert from "node:assert/strict";

test("passes", () => {
  assert.equal(1, 1);
});
`);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, json: true });
  config._suppressProgress = true;
  const output = [];
  const originalLog = console.log;

  console.log = (...args) => {
    output.push(args.join(" "));
  };

  try {
    await runUpdate(root, config);
  } finally {
    console.log = originalLog;
  }

  assert.equal(output.length, 1);
  const payload = JSON.parse(output[0]);
  assert.equal(payload.command, "up");
  assert.equal(payload.validation.passed, true);
  assert.equal(payload.tests.status, "passed");
});

test("detectTestCommand prefers the declared package manager", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-test-command-"));
  await fs.writeFile(path.join(root, "package.json"), JSON.stringify({
    packageManager: "pnpm@9.0.0",
    scripts: {
      test: "vitest run"
    }
  }, null, 2));

  const result = await detectTestCommand(root);

  assert.deepEqual(result, { command: "pnpm", args: ["test"] });
});

test("detectTestCommand falls back to lockfile detection", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-test-lockfile-"));
  await fs.writeFile(path.join(root, "package.json"), JSON.stringify({
    scripts: {
      test: "jest"
    }
  }, null, 2));
  await fs.writeFile(path.join(root, "yarn.lock"), "");

  const result = await detectTestCommand(root);

  assert.deepEqual(result, { command: "yarn", args: ["test"] });
});

test("runDoc reuses cached module artifacts when bounded content is unchanged", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-doc-cache-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: true });
  await runScan(root, config);
  await runDoc(root, config);

  const outputs = [];
  const originalLog = console.log;
  console.log = (...args) => {
    outputs.push(args.join(" "));
  };

  try {
    await runDoc(root, config);
  } finally {
    console.log = originalLog;
  }

  const docResult = outputs
    .map((line) => {
      try {
        return JSON.parse(line);
      } catch {
        return null;
      }
    })
    .find((item) => item?.command === "doc");

  assert.equal(docResult?.cached_manager_plan, true);
  assert.equal(docResult?.cached_modules, 1);

  const runDir = path.join(root, ".agents", "runs");
  const runFiles = (await fs.readdir(runDir)).sort();
  const latestRun = JSON.parse(await fs.readFile(path.join(runDir, runFiles.at(-1)), "utf8"));
  assert.equal(latestRun.results.cached_manager_plan, true);
  assert.equal(latestRun.results.cached_modules, 1);
  const db = openIndexDatabase(root);
  try {
    const meta = getRepoMeta(db);
    const managerPlanArtifact = getArtifact(db, "manager-plan");
    const moduleArtifact = getArtifact(db, "module-doc:auth");
    assert.equal(meta.module_count, 1);
    assert.ok(managerPlanArtifact);
    assert.match(moduleArtifact?.payload?.metadata?.freshness?.content_fingerprint || "", /^[a-f0-9]{64}$/);
  } finally {
    closeIndexDatabase(db);
  }
});

test("runDoc refreshes cached markdown and summary with current module metadata", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-doc-cache-refresh-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false });
  await runScan(root, config);
  await runDoc(root, config);

  const db = openIndexDatabase(root);
  try {
    const artifact = getArtifact(db, "module-doc:auth");
    artifact.payload.markdown = "# auth\n\n- Root: `undefined`\n";
    artifact.payload.metadata = {
      ...artifact.payload.metadata,
      module: {
        ...artifact.payload.metadata.module,
        root_path: undefined,
      },
      summary: "auth owns code under undefined and is indexed from src/auth/index.ts.",
    };
    upsertArtifact(db, {
      key: artifact.key,
      type: artifact.type,
      scope: artifact.scope,
      fingerprint: artifact.fingerprint,
      payload: artifact.payload,
      updatedAt: new Date().toISOString(),
    });
  } finally {
    closeIndexDatabase(db);
  }

  await runDoc(root, config);

  const moduleDoc = await fs.readFile(path.join(root, "docs", "modules", "auth.md"), "utf8");
  const repoDoc = await fs.readFile(path.join(root, "AGENTIFY.md"), "utf8");
  assert.doesNotMatch(moduleDoc, /undefined/);
  assert.doesNotMatch(repoDoc, /undefined/);
  assert.match(moduleDoc, /src\/auth/);
});
