import test from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import { applyHeaderToSource, renderHeader } from "../src/core/headers.js";
import { loadConfig } from "../src/core/config.js";
import { runDoc, runScan, runUpdate } from "../src/core/commands.js";
import { closeIndexDatabase, openIndexDatabase } from "../src/core/db/connection.js";
import { getArtifact, removeArtifact, upsertArtifact } from "../src/core/db/artifact-store.js";
import { getRepoMeta } from "../src/core/db/metadata-store.js";
import { validateRepo } from "../src/core/validate.js";

const execFileAsync = promisify(execFile);

async function initGitRepo(root) {
  await execFileAsync("git", ["init"], { cwd: root });
  await execFileAsync("git", ["config", "user.name", "Agentify Tests"], { cwd: root });
  await execFileAsync("git", ["config", "user.email", "agentify-tests@example.com"], { cwd: root });
  await execFileAsync("git", ["add", "."], { cwd: root });
  await execFileAsync("git", ["commit", "-m", "initial"], { cwd: root });
}

async function createRepoWithScriptedTest(prefix, exitCode) {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), prefix));
  await fs.writeFile(path.join(root, "package.json"), JSON.stringify({
    scripts: {
      test: "node test-result.js"
    }
  }, null, 2));
  await fs.writeFile(path.join(root, "test-result.js"), `process.exit(${exitCode});\n`);
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  return root;
}

async function readLatestRunReport(root, commandName) {
  const runDir = path.join(root, ".agents", "runs");
  const runFiles = (await fs.readdir(runDir))
    .filter((file) => file.endsWith(`-${commandName}.json`))
    .sort();
  assert.ok(runFiles.length > 0, `expected a persisted ${commandName} run report`);
  return JSON.parse(await fs.readFile(path.join(runDir, runFiles.at(-1)), "utf8"));
}

test("scan and doc generate required artifacts", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-update-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: true });
  await runScan(root, config);
  await runDoc(root, config);
  const result = await validateRepo(root, config);

  assert.equal(result.passed, true);
  assert.equal(await fs.stat(path.join(root, ".agents", "index.db")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, "src", "auth", "AGENTIFY.md")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, "AGENTIFY.md")).then(() => true), true);
  const summary = await fs.readFile(path.join(root, "AGENTIFY.md"), "utf8");
  assert.match(summary, /# AGENTIFY\.md/);
  assert.match(summary, /## Run Metrics/);
});

test("validateRepo allows tracked header-only code changes", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-validate-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  const filePath = path.join(root, "src", "auth", "index.ts");
  const source = "export const login = () => true;\n";
  await fs.writeFile(filePath, source);
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, docs: true });
  await runScan(root, config);
  await runDoc(root, config);

  const header = renderHeader({
    moduleName: "auth",
    summary: "Authentication entrypoints refreshed",
    relativePath: "src/auth/index.ts",
    stack: "ts"
  });
  const current = await fs.readFile(filePath, "utf8");
  await fs.writeFile(filePath, applyHeaderToSource(current, header), "utf8");

  const result = await validateRepo(root, config);

  assert.equal(result.passed, true);
});

test("validateRepo allows .agentify.yaml generated by init workflow", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-validate-config-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, docs: true });
  await runScan(root, config);
  await runDoc(root, config);
  await fs.writeFile(path.join(root, ".agentify.yaml"), "provider: local\n", "utf8");

  const result = await validateRepo(root, config);

  assert.equal(result.passed, true);
});

test("validateRepo hook mode allows ordinary tracked source edits", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-validate-hookmode-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  const filePath = path.join(root, "src", "auth", "index.ts");
  await fs.writeFile(filePath, "export const login = () => true;\n");
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, docs: true });
  await runScan(root, config);
  await runDoc(root, config);

  await fs.writeFile(filePath, "export const login = () => false;\nexport const logout = () => true;\n", "utf8");

  const strict = await validateRepo(root, config);
  const codeBodyFailures = strict.failures.filter((failure) => failure.category === "code-body-changed");
  assert.ok(codeBodyFailures.length > 0, "default check should still flag body changes");

  const hookMode = await validateRepo(root, config, { skipCodeBodyChanges: true });
  const hookCodeBodyFailures = hookMode.failures.filter((failure) => failure.category === "code-body-changed");
  assert.equal(hookCodeBodyFailures.length, 0, "hook-mode check should not flag intentional source edits");
});

test("validateRepo hook mode still reports unsafe changed paths", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-validate-hookmode-unsafe-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, docs: true });
  await runScan(root, config);
  await runDoc(root, config);

  await fs.writeFile(path.join(root, "scratch.txt"), "temporary notes\n", "utf8");

  const hookMode = await validateRepo(root, config, { skipCodeBodyChanges: true });
  const unsafeFailures = hookMode.failures.filter((failure) => failure.category === "unsafe-path");
  assert.equal(unsafeFailures.length, 1);
  assert.equal(unsafeFailures[0].path, "scratch.txt");
});

test("validateRepo allows project-scoped skill installations", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-validate-skills-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, docs: true });
  await runScan(root, config);
  await runDoc(root, config);
  await fs.mkdir(path.join(root, ".codex", "skills", "grill-me"), { recursive: true });
  await fs.writeFile(path.join(root, ".codex", "skills", "grill-me", "SKILL.md"), "# skill\n", "utf8");

  const result = await validateRepo(root, config);

  assert.equal(result.passed, true);
});

test("runUpdate emits percentage progress logs", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-progress-"));
  await fs.writeFile(path.join(root, "package.json"), JSON.stringify({
    scripts: {
      test: "node --test"
    }
  }, null, 2));
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.mkdir(path.join(root, "test"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await fs.writeFile(path.join(root, "test", "pass.test.js"), `import test from "node:test";
import assert from "node:assert/strict";

test("passes", () => {
  assert.equal(1, 1);
});
`);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, docs: true });
  const stderrChunks = [];
  const stdoutMessages = [];
  const originalWrite = process.stderr.write.bind(process.stderr);
  const originalLog = console.log;

  process.stderr.write = ((chunk, encoding, callback) => {
    stderrChunks.push(String(chunk));
    return originalWrite(chunk, encoding, callback);
  });
  console.log = (...args) => {
    stdoutMessages.push(args);
  };

  try {
    await runUpdate(root, config);
  } finally {
    process.stderr.write = originalWrite;
    console.log = originalLog;
  }

  const stderr = stderrChunks.join("");
  assert.match(stderr, /up: 0% starting/);
  assert.match(stderr, /up: 33% scan complete/);
  assert.match(stderr, /up: 67% doc complete/);
  assert.match(stderr, /up: 100% validation passed/);
  assert.match(stderr, /doc: 100% completed/);
  assert.ok(stdoutMessages.length > 0);
  assert.equal(await fs.stat(path.join(root, "output.txt")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, "agentify-report.html")).then(() => true), true);
  const output = await fs.readFile(path.join(root, "output.txt"), "utf8");
  assert.match(output, /\[agentify\] tests: passed/);
});

test("runUpdate in ghost mode reuses a single artifact root", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-ghost-update-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await initGitRepo(root);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, ghost: true, docs: true });
  await runUpdate(root, config);

  const sessionRoot = path.join(root, ".current_session");
  const ghostRuns = (await fs.readdir(sessionRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory() && entry.name.startsWith("ghost_"))
    .map((entry) => entry.name);

  assert.equal(ghostRuns.length, 1);

  const artifactRoot = path.join(sessionRoot, ghostRuns[0]);
  assert.equal(await fs.stat(path.join(artifactRoot, ".agents", "index.db")).then(() => true), true);
  assert.equal(await fs.stat(path.join(artifactRoot, "AGENTIFY.md")).then(() => true), true);
  assert.equal(await fs.stat(path.join(artifactRoot, "ghost-report.json")).then(() => true), true);
  assert.equal(await fs.stat(path.join(artifactRoot, "output.txt")).then(() => true), true);
  assert.equal(await fs.stat(path.join(artifactRoot, "agentify-report.html")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, ".agents", "index.db")).then(() => true).catch(() => false), false);
  assert.equal(await fs.stat(path.join(root, "output.txt")).then(() => true).catch(() => false), false);
  assert.equal(await fs.stat(path.join(root, "agentify-report.html")).then(() => true).catch(() => false), false);
});

test("runUpdate with json emits only the final payload", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-update-json-"));
  await fs.writeFile(path.join(root, "package.json"), JSON.stringify({
    scripts: {
      test: "node --test"
    }
  }, null, 2));
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.mkdir(path.join(root, "test"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await fs.writeFile(path.join(root, "test", "pass.test.js"), `import test from "node:test";
import assert from "node:assert/strict";

test("passes", () => {
  assert.equal(1, 1);
});
`);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, json: true });
  config._suppressProgress = true;
  const output = [];
  const originalLog = console.log;

  console.log = (...args) => {
    output.push(args.join(" "));
  };

  try {
    await runUpdate(root, config);
  } finally {
    console.log = originalLog;
  }

  assert.equal(output.length, 1);
  const payload = JSON.parse(output[0]);
  assert.equal(payload.command, "up");
  assert.equal(payload.validation.passed, true);
  assert.equal(payload.tests.status, "passed");
});

test("runUpdate reports malformed package.json as a failed test discovery", async () => {
  const previousExitCode = process.exitCode;
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-update-malformed-pkg-"));
  const packageJsonPath = path.join(root, "package.json");
  await fs.writeFile(packageJsonPath, "{ invalid json\n", "utf8");
  await fs.mkdir(path.join(root, "src"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "index.js"), "export const ok = true;\n", "utf8");

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, json: true });
  config._suppressProgress = true;
  const output = [];
  const originalLog = console.log;

  console.log = (...args) => {
    output.push(args.join(" "));
  };

  try {
    process.exitCode = undefined;
    const finalOutput = await runUpdate(root, config);

    assert.equal(output.length, 1);
    const payload = JSON.parse(output[0]);
    assert.equal(payload.validation.passed, true);
    assert.equal(payload.tests.status, "failed");
    assert.equal(payload.tests.passed, false);
    assert.equal(payload.tests.command, null);
    assert.equal(payload.tests.exit_code, null);
    assert.deepEqual(payload, finalOutput);
    assert.equal(payload.tests.discovery_error.type, "package_json_parse_error");
    assert.equal(payload.tests.discovery_error.path, packageJsonPath);
    assert.equal(process.exitCode, 1);
  } finally {
    console.log = originalLog;
    process.exitCode = previousExitCode;
  }
});

test("runUpdate persists test metadata for passing and failing up and sync run reports", async () => {
  const previousExitCode = process.exitCode;
  const cases = [
    { commandName: "up", exitCode: 0, expectedStatus: "passed", expectedPassed: true },
    { commandName: "up", exitCode: 1, expectedStatus: "failed", expectedPassed: false },
    { commandName: "sync", exitCode: 0, expectedStatus: "passed", expectedPassed: true },
    { commandName: "sync", exitCode: 1, expectedStatus: "failed", expectedPassed: false },
  ];

  try {
    for (const testCase of cases) {
      process.exitCode = undefined;
      const root = await createRepoWithScriptedTest(`agentify-${testCase.commandName}-persist-tests-`, testCase.exitCode);
      const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: true, json: true });
      const originalLog = console.log;
      console.log = () => {};

      let finalOutput;
      try {
        finalOutput = await runUpdate(root, config, { commandName: testCase.commandName });
      } finally {
        console.log = originalLog;
      }

      const persistedRun = await readLatestRunReport(root, testCase.commandName);
      for (const tests of [finalOutput.tests, persistedRun.tests]) {
        assert.equal(tests.status, testCase.expectedStatus);
        assert.equal(tests.passed, testCase.expectedPassed);
        assert.equal(tests.command, "npm test");
        assert.equal(tests.stdout_truncated, false);
        assert.equal(tests.stderr_truncated, false);
        assert.equal(typeof tests.stdout_bytes, "number");
        assert.equal(typeof tests.stderr_bytes, "number");
        assert.equal(tests.output_max_bytes, 49152);
        assert.equal(tests.exit_code, testCase.exitCode);
      }
      assert.deepEqual(finalOutput.tests, persistedRun.tests);
    }
  } finally {
    process.exitCode = previousExitCode;
  }
});

test("runUpdate skips docs and headers by default unless docs=true is explicitly set", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-update-default-docs-off-"));
  await fs.writeFile(path.join(root, "package.json"), JSON.stringify({
    scripts: {
      test: "node --test"
    }
  }, null, 2));
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.mkdir(path.join(root, "test"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");
  await fs.writeFile(path.join(root, "test", "pass.test.js"), `import test from "node:test";
import assert from "node:assert/strict";

test("passes", () => {
  assert.equal(1, 1);
});
`);

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false, docs: false });
  await runUpdate(root, config);

  assert.equal(await fs.stat(path.join(root, ".agents", "index.db")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, "AGENTIFY.md")).then(() => true).catch(() => false), false);
  const source = await fs.readFile(path.join(root, "src", "auth", "index.ts"), "utf8");
  assert.doesNotMatch(source, /@agentify/);
});

test("runDoc reuses cached module artifacts when bounded content is unchanged", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-doc-cache-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: true });
  await runScan(root, config);
  await runDoc(root, config);

  const outputs = [];
  const originalLog = console.log;
  console.log = (...args) => {
    outputs.push(args.join(" "));
  };

  try {
    await runDoc(root, config);
  } finally {
    console.log = originalLog;
  }

  const docResult = outputs
    .map((line) => {
      try {
        return JSON.parse(line);
      } catch {
        return null;
      }
    })
    .find((item) => item?.command === "doc");

  assert.equal(docResult?.cached_manager_plan, true);
  assert.equal(docResult?.cached_modules, 1);
  assert.deepEqual(docResult?.provider_status, {
    status: "fallback",
    provider: "local",
    mode: "deterministic-local"
  });

  const runDir = path.join(root, ".agents", "runs");
  const runFiles = (await fs.readdir(runDir)).sort();
  const latestRun = JSON.parse(await fs.readFile(path.join(runDir, runFiles.at(-1)), "utf8"));
  assert.equal(latestRun.results.cached_manager_plan, true);
  assert.equal(latestRun.results.cached_modules, 1);
  assert.deepEqual(latestRun.provider_status, {
    status: "fallback",
    provider: "local",
    mode: "deterministic-local"
  });
  const db = openIndexDatabase(root);
  try {
    const meta = getRepoMeta(db);
    const managerPlanArtifact = getArtifact(db, "manager-plan");
    const moduleArtifact = getArtifact(db, "module-doc:auth");
    assert.equal(meta.module_count, 1);
    assert.ok(managerPlanArtifact);
    assert.deepEqual(moduleArtifact?.payload?.metadata?.provider_status, {
      status: "fallback",
      provider: "local",
      mode: "deterministic-local"
    });
    assert.match(moduleArtifact?.payload?.metadata?.freshness?.content_fingerprint || "", /^[a-f0-9]{64}$/);
  } finally {
    closeIndexDatabase(db);
  }
});

test("runDoc fails closed when an external module provider stalls", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-doc-provider-timeout-"));
  const binDir = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-doc-provider-bin-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");

  const codexPath = path.join(binDir, "codex");
  await fs.writeFile(codexPath, `#!/usr/bin/env node
setInterval(() => {}, 1000);
`, "utf8");
  await fs.chmod(codexPath, 0o755);

  const previousPath = process.env.PATH;
  process.env.PATH = `${binDir}${path.delimiter}${previousPath || ""}`;

  try {
    const config = await loadConfig(root, {
      provider: "codex",
      dryRun: false,
      tokenReport: false,
      providerTimeoutMs: 50,
    });
    await runScan(root, config, { skipOutput: true });
    const localConfig = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false });
    await runDoc(root, localConfig, { skipOutput: true });
    const db = openIndexDatabase(root);
    try {
      removeArtifact(db, "module-doc:auth");
    } finally {
      closeIndexDatabase(db);
    }
    await fs.unlink(path.join(root, "docs", "modules", "auth.md"));
    assert.equal(await fs.stat(path.join(root, "docs", "repo-map.md")).then(() => true), true);

    await assert.rejects(
      () => runDoc(root, config, { skipOutput: true }),
      /doc provider "codex" failed while generating module "auth".*timed out/,
    );

    assert.equal(await fs.stat(path.join(root, "docs", "repo-map.md")).then(() => true).catch(() => false), false);
    assert.equal(await fs.stat(path.join(root, "src", "auth", "AGENTIFY.md")).then(() => true).catch(() => false), false);
    assert.equal(await fs.stat(path.join(root, ".agents", ".lock")).then(() => true).catch(() => false), false);
  } finally {
    if (previousPath === undefined) {
      delete process.env.PATH;
    } else {
      process.env.PATH = previousPath;
    }
  }

  const localConfig = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false });
  await runDoc(root, localConfig, { skipOutput: true });

  assert.equal(await fs.stat(path.join(root, "docs", "repo-map.md")).then(() => true), true);
  assert.equal(await fs.stat(path.join(root, "src", "auth", "AGENTIFY.md")).then(() => true), true);
});

test("runDoc refreshes cached markdown and summary with current module metadata", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "agentify-doc-cache-refresh-"));
  await fs.writeFile(path.join(root, "package.json"), "{}\n");
  await fs.mkdir(path.join(root, "src", "auth"), { recursive: true });
  await fs.writeFile(path.join(root, "src", "auth", "index.ts"), "export const login = () => true;\n");

  const config = await loadConfig(root, { provider: "local", dryRun: false, tokenReport: false });
  await runScan(root, config);
  await runDoc(root, config);

  const db = openIndexDatabase(root);
  try {
    const artifact = getArtifact(db, "module-doc:auth");
    artifact.payload.markdown = "# auth\n\n- Root: `undefined`\n";
    artifact.payload.metadata = {
      ...artifact.payload.metadata,
      module: {
        ...artifact.payload.metadata.module,
        root_path: undefined,
      },
      summary: "auth owns code under undefined and is indexed from src/auth/index.ts.",
    };
    upsertArtifact(db, {
      key: artifact.key,
      type: artifact.type,
      scope: artifact.scope,
      fingerprint: artifact.fingerprint,
      payload: artifact.payload,
      updatedAt: new Date().toISOString(),
    });
  } finally {
    closeIndexDatabase(db);
  }

  await runDoc(root, config);

  const moduleDoc = await fs.readFile(path.join(root, "src", "auth", "AGENTIFY.md"), "utf8");
  const repoDoc = await fs.readFile(path.join(root, "AGENTIFY.md"), "utf8");
  assert.doesNotMatch(moduleDoc, /undefined/);
  assert.doesNotMatch(repoDoc, /undefined/);
  assert.match(moduleDoc, /src\/auth/);
});
